controller_manager:
  ros__parameters:
    update_rate: 30 # Has to be an integer otherwise errors are encountered
    # use_sim_time: true # This setting is propagated to the diff_controller below

    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    
    publish_rate: 50.0 # Has to be double otherwise errors are encountered

    base_frame_id: base_footprint

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.134
    wheel_radius: 0.0335

    # Whether the input has a time stamp or not
    use_stamped_vel: false

# joint_broadcaster:
#   ros__parameters:
    